"""Add image_url to certificates

Revision ID: 838d5cfb2583
Revises: bd8771afdec8
Create Date: 2025-11-20 14:19:26.159245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '838d5cfb2583'
down_revision = 'bd8771afdec8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('certificates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('certificates', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
